---
title: "OSRI Tables"
output: html_document
date: "2025-09-03"
---

## Tables

```{r}
## Full Summary Table, to be combined with Region Table below
summary_table <- D19 %>%
  group_by(Data_source,Study_name_clean,Layman_group,  Sample_motivation, Sum_Method) %>%
  summarise(
    Observations = n(),
    Date_range = paste0(
      format(min(as.Date(Year_clean, format = "%Y"), na.rm = TRUE), "%Y"),
      " - ",
      format(max(as.Date(Year_clean, format = "%Y"), na.rm = TRUE), "%Y")
    ),
    Max_Total_PAH = max(Total_PAH, na.rm = TRUE),
    Min_Total_PAH = min(Total_PAH, na.rm = TRUE),
    Mean_Total_PAH = mean(Total_PAH, na.rm = TRUE),
    Median_Total_PAH = median(Total_PAH, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  arrange(Layman_group, Data_source)
write_xlsx(summary_table, "Tables/OSRI_Table1.xlsx")

#Table 1 with regions defined (different data set)
summary_table <- D20 %>%
  group_by(Data_source,Study_name_clean,Layman_group,  Sample_motivation, Sum_Method,Region) %>%
  summarise(
    Observations = n(),
    Date_range = paste0(
      format(min(as.Date(Year_clean, format = "%Y"), na.rm = TRUE), "%Y"),
      " - ",
      format(max(as.Date(Year_clean, format = "%Y"), na.rm = TRUE), "%Y")
    ),
    .groups = "drop"
  ) %>%
  arrange(Layman_group, Data_source)
write_xlsx(summary_table, "OSRI_Table1region.xlsx")

#Condensed Version of Table 1
summary_table_condensed <- D19 %>%
  group_by(Data_source,Study_name_clean, Sample_motivation, Sum_Method) %>%
  summarise(
    Layman_groups = paste(unique(Layman_group), collapse = ", "),
    Observations = n(),
    Date_range = paste0(
      format(min(as.Date(Year_clean, format = "%Y"), na.rm = TRUE), "%Y"),
      " - ",
      format(max(as.Date(Year_clean, format = "%Y"), na.rm = TRUE), "%Y")
    ),
    .groups = "drop"
  ) %>%
  arrange(Data_source, Sample_motivation)
write_xlsx(summary_table_condensed, "Tables/OSRI_Table1condensed.xlsx")
```

#Make a Table on Sampling effort verse Recorded Harvest by Region
```{r}
summary_table1 <- D20 %>% # Make the Observations data ready to compare to harvest data
  mutate(Taxa= case_when(
    Layman_group=="Seaweed"~"Plants", 
    Layman_group=="Snails"~"Invertebrate", 
    Layman_group=="Urchins/ Starfish"~"Invertebrate", 
    Layman_group=="Octopus"~"Invertebrate", 
    Layman_group=="Clams"~"Invertebrate", 
    Layman_group=="Mussels"~"Invertebrate", 
    Layman_group=="Crabs/ Shrimp"~"Invertebrate", 
    Layman_group=="Fish"~"Fish", 
    Layman_group=="Seals/ Whales"~ "Marine Mammals"
  ))%>%
  group_by(Taxa,Region) %>%
  summarise(
    Observations = n(),
    .groups = "drop"
  ) %>%
  arrange(Taxa, Region)
subs<- read_csv("subsistence_summary_by_community_coastal.csv") # load harvest data summarized by Will

subs1<-subs%>%
  mutate(Region= case_when(
    is.na(Region) ~ "West",
    TRUE~Region))%>%
  group_by(Region)%>%
  summarise(
    Invertebrate = sum(MarineInverts_kg, na.rm = TRUE),
    Fish = sum(Fish_kg, na.rm = TRUE),
    `Marine Mammals` = sum(MarineMammals_kg, na.rm = TRUE),
    .groups = "drop"
  )

subs2<-subs1%>%
  pivot_longer(
    cols = c(Invertebrate, Fish, `Marine Mammals`), 
    names_to = "Taxa",           
    values_to = "Kilos"           
 )

joined_df <- full_join(subs2, summary_table1, by = c("Region", "Taxa"))


```

Data Quality

```{r}



```